#Copyright Snap Inc. 2021. This sample code is made available by Snap Inc. for informational purposes only.
#No license, whether implied or otherwise, is granted in or to such code (including any rights to copy, modify,
#publish, distribute and/or commercialize such code), unless you have entered into a separate agreement for such rights.
#Such code is provided as-is, without warranty of any kind, express or implied, including any warranties of merchantability,
#title, fitness for a particular purpose, non-infringement, or that such code is free of defects, errors or viruses.
#In no event will Snap Inc. be liable for any damages or losses of any kind arising from the sample code or your use thereof.

experiment_name: cityscapes128

dataset_params:
  root_dir: /home/ubuntu/zzc/data/video_prediction/dataset_h5/cityscapes_h5
  frame_shape: 128
  augmentation_params:
    flip_param:
      horizontal_flip: True
      time_flip: False
    jitter_param:
      brightness: 0.1
      contrast: 0.1
      saturation: 0.1
      hue: 0.1
  min_frame_distance: 0
  max_frame_distance: 30
  train_params:
    type: train
    cond_frames: 2
    pred_frames: 5
  valid_params:
    total_videos: 256
    type: test
    cond_frames: 2
    pred_frames: 28

flow_params:
  model_params:
    num_regions: 20
    num_channels: 3
    estimate_affine: True
    revert_axis_swap: True
    bg_predictor_params:
      block_expansion: 32
      max_features: 1024
      num_blocks: 5
      bg_type: 'perspective' # 'zero', 'shift', 'affine', 'perspective'
    region_predictor_params:
      temperature: 0.1
      block_expansion: 32
      max_features: 1024
      scale_factor: 0.25
      num_blocks: 5
      pca_based: True
      pad: 0
      fast_svd: False
    generator_params:
      block_expansion: 64
      max_features: 512
      num_down_blocks: 2
      num_bottleneck_blocks: 6
      skips: True
      pixelwise_flow_predictor_params:
        block_expansion: 64
        max_features: 1024
        num_blocks: 5
        scale_factor: 0.25
        use_deformed_source: True
        use_covar_heatmap: True
        estimate_occlusion_map: True
  train_params:
    max_epochs: 432
    num_repeats: 20
    scheduler_param:
      milestones: [20000, 40000]
      gamma: 0.5
    lr: 2.0e-4
    batch_size: 128
    valid_batch_size: 256
    dataloader_workers: 8
    print_freq: 500
    save_img_freq: 2500
    update_ckpt_freq: 2500
    save_ckpt_freq: 10000
    scales: [1, 0.5, 0.25, 0.125]
    transform_params:
      sigma_affine: 0.05
      sigma_tps: 0.005
      points_tps: 5
    loss_weights:
      perceptual: [10, 10, 10, 10, 10]
      equivariance_shift: 10
      equivariance_affine: 10

diffusion_params:
  model_params:
    null_cond_prob: 0.0
    use_residual_flow: False
    only_use_flow: False
    sampling_timesteps: 10
    loss_type: 'l2'
    ada_layers: 'auto'
  train_params:
    max_epochs: 100000
    num_repeats: 1
    scheduler_param:
      milestones: [100000, 150000]
      gamma: 0.75
    lr: 1.2e-4
    batch_size: 32
    valid_batch_size: 8
    dataloader_workers: 32
    print_freq: 100
    save_img_freq: 1000
    save_vid_freq: 1000
    update_ckpt_freq: 1000
    save_ckpt_freq: 5000

visualizer_params:
  kp_size: 2
  draw_border: True
  colormap: 'gist_rainbow'
  region_bg_color: [1, 1, 1]