#Copyright Snap Inc. 2021. This sample code is made available by Snap Inc. for informational purposes only.
#No license, whether implied or otherwise, is granted in or to such code (including any rights to copy, modify,
#publish, distribute and/or commercialize such code), unless you have entered into a separate agreement for such rights.
#Such code is provided as-is, without warranty of any kind, express or implied, including any warranties of merchantability,
#title, fitness for a particular purpose, non-infringement, or that such code is free of defects, errors or viruses.
#In no event will Snap Inc. be liable for any damages or losses of any kind arising from the sample code or your use thereof.

experiment_name: ucf101_64

dataset_params:
  root_dir: /home/ubuntu/zzc/data/UCF101_h5
  frame_shape: 64
  augmentation_params:
    flip_param:
      horizontal_flip: True
      time_flip: False
    jitter_param:
      brightness: 0.1
      contrast: 0.1
      saturation: 0.1
      hue: 0.1
  min_frame_distance: 0
  max_frame_distance: 20
  train_params:
    type: train
    cond_frames: 4
    pred_frames: 8
  valid_params:
    total_videos: 256
    type: test
    cond_frames: 4
    pred_frames: 16

flow_params:
  model_params:
    embed_dim: 4
    ddconfig:
      double_z: False
      channels: 384
      resolution: 256
      timesteps: 16
      skip: 1
      in_channels: 3
      out_ch: 3
      num_res_blocks: 2
      attn_resolutions: []
      splits: 1
  train_params:
    max_epochs: 21 # 21 for 100, 54 for bs256
    num_repeats: 100
    scheduler_param:
      milestones: [100000, 150000]
      gamma: 0.8
    lr: 2.0e-4
    batch_size: 100 # 100, 256
    valid_batch_size: 256
    dataloader_workers: 8
    print_freq: 100
    save_img_freq: 5000
    update_ckpt_freq: 5000
    save_ckpt_freq: 5000
    scales: [1, 0.5, 0.25]
    transform_params:
      sigma_affine: 0.05
      sigma_tps: 0.005
      points_tps: 5
    loss_weights:
      perceptual: [10, 10, 10, 10, 10]
      equivariance_shift: 10
      equivariance_affine: 10

diffusion_params:
  model_params:
    null_cond_prob: 0.0
    use_residual_flow: False
    only_use_flow: False
    sampling_timesteps: 10
    loss_type: 'l2'
  train_params:
    max_epochs: 134
    num_repeats: 4
    scheduler_param:
      milestones: [100000, 150000]
      gamma: 0.8
    lr: 2.0e-4
    batch_size: 24
    valid_batch_size: 32
    dataloader_workers: 16
    print_freq: 50
    save_img_freq: 1000
    save_vid_freq: 1000
    update_ckpt_freq: 1000
    save_ckpt_freq: 1000

visualizer_params:
  kp_size: 2
  draw_border: True
  colormap: 'gist_rainbow'
  region_bg_color: [1, 1, 1]