wandb_version: 1

_wandb:
  desc: null
  value:
    python_version: 3.9.15
    cli_version: 0.15.5
    is_jupyter_run: false
    is_kaggle_kernel: true
    start_time: 1690376386.643448
    t:
      1:
      - 55
      2:
      - 55
      3:
      - 13
      - 23
      4: 3.9.15
      5: 0.15.5
      8:
      - 2
      - 5
