#Copyright Snap Inc. 2021. This sample code is made available by Snap Inc. for informational purposes only.
#No license, whether implied or otherwise, is granted in or to such code (including any rights to copy, modify,
#publish, distribute and/or commercialize such code), unless you have entered into a separate agreement for such rights.
#Such code is provided as-is, without warranty of any kind, express or implied, including any warranties of merchantability,
#title, fitness for a particular purpose, non-infringement, or that such code is free of defects, errors or viruses.
#In no event will Snap Inc. be liable for any damages or losses of any kind arising from the sample code or your use thereof.

experiment_name: carla128

dataset_params:
  root_dir: /mnt/sda/hjy/fdm/CARLA_Town_01_h5
  frame_shape: 128
  min_frame_distance: 0
  max_frame_distance: 100
  augmentation_params:
    flip_param:
      horizontal_flip: True
      time_flip: False
    jitter_param:
      brightness: 0.1
      contrast: 0.1
      saturation: 0.1
      hue: 0.1

valid_dataset_params:
  total_videos: 100
  type: test
  cond_frames: 2
  pred_frames: 28

model_params:
  num_regions: 20
  num_channels: 3
  estimate_affine: True
  revert_axis_swap: True
  bg_predictor_params:
    block_expansion: 32
    max_features: 1024
    num_blocks: 5
    bg_type: 'affine'
  region_predictor_params:
    temperature: 0.1
    block_expansion: 32
    max_features: 1024
    scale_factor: 0.25
    num_blocks: 5
    pca_based: True
    pad: 0
    fast_svd: False
  generator_params:
    block_expansion: 64
    max_features: 512
    num_down_blocks: 2
    num_bottleneck_blocks: 6
    skips: True
    pixelwise_flow_predictor_params:
      block_expansion: 64
      max_features: 1024
      num_blocks: 5
      scale_factor: 0.25
      use_deformed_source: True
      use_covar_heatmap: True
      estimate_occlusion_map: True
  avd_network_params:
    id_bottle_size: 64
    pose_bottle_size: 64

train_params:
  max_epochs: 246
  num_repeats: 200
  batch_size: 100
  dataloader_workers: 8
  epoch_milestones: [60, 90]
  lr: 2.0e-4
  print_freq: 100
  save_img_freq: 500
  update_ckpt_freq: 500
  scales: [1, 0.5, 0.25, 0.125]
  transform_params:
    sigma_affine: 0.05
    sigma_tps: 0.005
    points_tps: 5
  loss_weights:
    perceptual: [10, 10, 10, 10, 10]
    equivariance_shift: 10
    equivariance_affine: 10

save_ckpt_freq: 2000

visualizer_params:
  kp_size: 3
  draw_border: True
  colormap: 'gist_rainbow'
  region_bg_color: [1, 1, 1]

# num_example_per_epoch = num_repeats * len                      = 200 * 408    = 81600
# num_step_per_epoch    = ceil(num_example_per_epoch/batch_size) = 81600 / 100 = 816
# final_step            = num_step_per_epoch * max_epochs        = 816 * 246   = 200736
# save_ckpt_freq        = 2000